### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by 3kh0** [ReedGraf/isd279games#1]
Hello there!

I was just questioning what you are trying to do with my code. You had withdrawn my name from it so I assume you are not trying to develop it. This was code that I got and it could land you in some legal problems if you try and steal it. I am awaiting your response.

Echo

**Comment by ReedGraf** [comment]
I am aware this response is replied automatically, however, I've updated the repo to include your name. I haven't done anything to your code itself and it shall remain the same. Currently, your code is in the pre-release, but a full release should happen in a day or so. If you'd like anything else feel free to ask! ❤️
-Reed Graf :D

**Comment by 3kh0** [comment]
Hello again!

Thank you for your speedy response. I have rechecked the website and my name is nowhere to be found. If you are confused on which site I am talking about the google site. But upon further, look on this website, I want to merge with your site, if you want to look here is my site, fully built by me: [3kh0.github.io](https://3kh0.github.io/) It attracts over 10k views per weekday and somehow on weekends it gets up to 500 views. 
I am awaiting your response.

Cheers!
Echo
